### ISSUE TITLE
Build Error when building release with debug info for profiling.

### ISSUE THREAD

**Issue by Thell** [rust-or/highs-sys#11]
```
-- Build files have been written to: C:/Users/thell/Workspaces/bdo/housecraft/target/release/build/highs-sys-92234839f67e8789/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "RelWithDebInfo" "--parallel" "16"
  MSBuild version 17.5.1+f6fdcf537 for .NET Framework

    Checking Build System
    Building Custom Rule C:/Users/thell/.cargo/git/checkouts/highs-sys-libz-228d8310235e4834/1ed2664/HiGHS/src/CMakeLists.txt
  cl : command line  error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\Users\thell\Workspaces\bdo\housecraft\target\release\build\highs-sys-92234839f67e8789\out\build\src\libhighs.vcxproj]
```

Builds just fine without

```
[profile.release]
debug = 1
```

According to [MSDN](https://learn.microsoft.com/en-us/cpp/build/reference/rtc-run-time-error-checks?view=msvc-170)

> If you compile your program at the command line using any of the /RTC compiler options, any pragma [optimize](https://learn.microsoft.com/en-us/cpp/preprocessor/optimize?view=msvc-170) instructions in your code silently fail. That's because run-time error checks aren't valid in a release (optimized) build.
> Use /RTC for development builds; Don't use /RTC for a release build. /RTC can't be used with compiler optimizations ([/O Options (Optimize Code)](https://learn.microsoft.com/en-us/cpp/build/reference/o-options-optimize-code?view=msvc-170)). A program image built with /RTC is slightly larger and slightly slower than an image built with /Od (up to 5 percent slower than an /Od build).

Perhaps something could be passed to CMake for the HiGHs build?

**Comment by galabovaa** [comment]
Fixed in https://github.com/ERGO-Code/HiGHS/tree/latest, will be included in our upcoming release.

**Comment by Thell** [comment]
Confirmed to be working. See <https://github.com/rust-or/highs-sys/issues/13>
