### ISSUE TITLE
Can't build a `Release` build on Windows with NDEBUG set.

### ISSUE THREAD

**Issue by Thell** [rust-or/highs-sys#13]
Regardless of if I build a release build or debug build the resulting lib has asserts enabled. I can build a Release build by building HiGHS directly _and_ building in WSL everything works, (Release, Debug, Release with debug info). I've tried passing NDEBUG=1 via the highs-sys build.rs but the CMake reports it as unused, which surprised me, lol.

Try as I might I can not figure out _where_ things are going wrong but this has a huge performance impact.

**Comment by Thell** [comment]
Using `.generator("Ninja")` in the `build.rs` config allows `Release` to be built. The RelWithDebInfo build still fails but that's hopefully going to get fixed in HiGHS cmake files.

I haven't tried using any of the ninja crates since I already have it installed but that might be something to look at.

**Comment by jajhall** [comment]
Why do you want to build HiGHS in anything other than `Release`?

**Comment by galabovaa** [comment]
Fixed in https://github.com/ERGO-Code/HiGHS/tree/latest, will be included in our upcoming release.

**Comment by Thell** [comment]
I just confirmed that it works without using `branch=latest` too, so yeah, I'll just close it.

Thanks again.
