### ISSUE TITLE
Updating to use HighS 1.5.3

### ISSUE THREAD

**Issue by tomchandler182** [rust-or/highs-sys#16]
Hi All, i was wondering if this package was going to be updated to 1.5.3 as I noticed they have released a new version which includes bug fixes. Thanks!

**Comment by lovasoa** [comment]
Yes that would be great. Do you want to make a PR ?

**Comment by tomchandler182** [comment]
@lovasoa I have created a PR https://github.com/rust-or/highs-sys/pull/17 however it seems the build is failing, i don't believe i have the knowledge to fix this one. The linking is all a bit magic to me :(

**Comment by tomchandler182** [comment]
Thanks! @lovasoa
