### ISSUE TITLE
highs-sys constantly triggers recompiles on macOS

### ISSUE THREAD

**Issue by yongqli** [rust-or/highs-sys#24]
On Rust 1.76 as well as Rust 1.75, highs-sys will constantly recompile. Steps to reproduce:

1) Clone the highs repo
2) Run `cargo check` in the `highs/` dir
3) Run `cargo check` again
4) Run `cargo check` again

Cargo will attempt to recompile highs-sys on each invocation.

With `export CARGO_LOG=cargo::core::compiler::fingerprint=trace`, the log shows:

    stale: changed "highs/target/debug/build/highs-sys-404d2adca8ba9629/out/highs.h"
              (vs) "highs/target/debug/build/highs-sys-404d2adca8ba9629/output"
                   FileTime { seconds: 1707718602, nanos: 124610939 } < FileTime { seconds: 1707718603, nanos: 359456182 }

**Comment by yongqli** [comment]
It seems that the difference is due to changing from `CargoCallbacks` to `CargoCallbacks::new()`, which changes the `rerun_on_header_files` setting in bindgen.

**Comment by lovasoa** [comment]
done
