### ISSUE TITLE
[General Question] How are the absences of lower and upper bound constraints handled?

### ISSUE THREAD

**Issue by DaveLanday** [rust-or/highs-sys#27]
Hi,
I have a general question. Let's say I read a model from a .mps file using `Highs_readModel()` and a row in the constraint matrix has an upper bound, but no lower bound constraint imposed on it (or vice-a-versa). How does highs or highs-sys handle this assignment in `row_upper` and/or `row_lower` ? Will the value at that index in row_lower be `f64::NEG_INFINITY` and/or `f64::INFINITY` in row_upper ?
Thanks for any clarification!

**Comment by jajhall** [comment]
HiGHS stores infinite bounds in C++ as

const double kHighsInf = std::numeric_limits<double>::infinity();

Presumably this maps to some equivalent in rust

**Comment by DaveLanday** [comment]
Excellent! Thank you for the response! I ask because I wrote my own feasibility check for LPs, but wasn't sure if I needed to handle the absence of a missing bound constraint a certain way
